nuevo_presupuesto:
    pattern:  /nuevo-presupuesto/{presupuesto}
    defaults: { _controller: PresupuestoBundle:Presupuesto:nuevo, presupuesto : null}
    
presupuesto_recepcion:
    pattern:  /presupuesto/recepcion/{presupuesto}
    defaults: { _controller: PresupuestoBundle:Presupuesto:recepcion }
    
presupuesto_trabajos:
    pattern:  /presupuesto/trabajos/{presupuesto}
    defaults: { _controller: PresupuestoBundle:Presupuesto:trabajos }

presupuesto_repuestos:
    pattern:  /presupuesto/repuestos/{presupuesto}
    defaults: { _controller: PresupuestoBundle:Presupuesto:repuestos } 
    
presupuesto_final:
    pattern:  /presupuesto/final/{presupuesto}
    defaults: { _controller: PresupuestoBundle:Presupuesto:final }  