nuevo_presupuesto:
    pattern:  /nuevo-presupuesto/{presupuesto}
    defaults: { _controller: PresupuestoBundle:Presupuesto:nuevo, presupuesto : null}
    
presupuesto_recepcion:
    pattern:  /presupuesto/recepcion/{presupuesto}
    defaults: { _controller: PresupuestoBundle:Presupuesto:recepcion }
    
presupuesto_trabajos:
    pattern:  /presupuesto/trabajos/{presupuesto}
<<<<<<< HEAD
    defaults: { _controller: PresupuestoBundle:Presupuesto:trabajos }
=======
    defaults: { _controller: PresupuestoBundle:Presupuesto:trabajos }
    
presupuesto_final:
    pattern:  /presupuesto/final/{presupuesto}
    defaults: { _controller: PresupuestoBundle:Presupuesto:final }  
>>>>>>> 0ed6520f86230f9517ae309dd415a4fba90a74a4
