nuevo_presupuesto:
    pattern:  /nuevo-presupuesto
    defaults: { _controller: PresupuestoBundle:Default:nuevo }
    
presupuesto_recepcion:
    pattern:  /presupuesto/recepcion/{presupuesto}
    defaults: { _controller: PresupuestoBundle:Default:recepcion }