<?php

namespace Piddo\ClienteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TelefonoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelefonoRepository extends EntityRepository
{
}
