<?php

namespace Piddo\ComponenteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponenteRepository extends EntityRepository
{
}
