componente:
    resource: "@ComponenteBundle/Resources/config/componenteRouting.yml"
    prefix:   /componente

recepcion:
    resource: "@RecepcionBundle/Resources/config/routing.yml"
    prefix:   /

repuesto:
    resource: "@RepuestoBundle/Resources/config/routing.yml"
    prefix:   /

presupuesto:
    resource: "@PresupuestoBundle/Resources/config/presupuestoRouting.yml"
    prefix:   /

cliente:
    resource: "@ClienteBundle/Resources/config/routing.yml"
    prefix:   /

taller:
    resource: "@TallerBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

motor:
    resource: "@MotorBundle/Resources/config/routing.yml"
    prefix:   /

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

