vistas:
    resource: "@VistasBundle/Resources/config/routing.yml"
    prefix:   /

presupuesto:
    resource: "@PresupuestoBundle/Resources/config/routing.yml"
    prefix:   /

cliente:
    resource: "@ClienteBundle/Resources/config/routing.yml"
    prefix:   /

taller:
    resource: "@TallerBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

motor:
    resource: "@MotorBundle/Resources/config/routing.yml"
    prefix:   /

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

