security:
    firewalls:
        prueba:
          pattern: ^/*
          anonymous: ~
    
    providers:
      usuarios:
        entity: { class: Piddo\UsuarioBundle\Entity\Usuario, property: rut}

    access_control:
      - { path: ^/privado, roles: ROLE_USUARIO }

    encoders:
      Piddo\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }