security:
    firewalls:
        prueba:
          pattern: ^/*
          anonymous: ~
          logout:
            path: usuario_logout
            target: /hello/Adios
          form_login:
            login_path: usuario_login
            check_path: usuario_login_check
            default_target_path: /hello/Usuario
    
    providers:
      usuarios:
        entity: { class: Piddo\UsuarioBundle\Entity\Usuario, property: rut}

    access_control:
      - { path: ^/privado, roles: ROLE_USUARIO }

    encoders:
      Piddo\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }