portada_gerencia:
    pattern:  /administracion/portada
    defaults: { _controller: AdminBundle:Default:portadaGerencia }
    
admin_marcas:
    pattern:  /administracion/marcas
    defaults: { _controller: AdminBundle:Default:marcas }
    
borrar_marca:
    pattern: /administracion/marcas/borrar-{marca}
    defaults: { _controller: AdminBundle:Default:borrarMarca }

admin_modelos:
    pattern: /administracion/{marca}/modelos
    defaults: { _controller: AdminBundle:Default:modelos }

borrar_modelo:
    pattern: /administracion/{marca}/borrar-{modelo}
    defaults: { _controller: AdminBundle:Default:borrarModelo }
    
admin_series:
    pattern: /administracion/{marca}/{modelo}/series
    defaults: { _controller: AdminBundle:Default:series }
 
borrar_serie:
    pattern: /administracion/{marca}/{modelo}/borrar-{serie}
    defaults: { _controller: AdminBundle:Default:borrarSerie }
    
admin_rectificados:
    pattern: /administracion/rectificados
    defaults: { _controller: AdminBundle:Rectificados:rectificados }