rectificado_universo:
    pattern: /universo
    defaults: { _controller: TallerBundle:Rectificados:universo }
    
rectificado_perfil:
    pattern: /{serie}/perfil
    defaults: { _controller: TallerBundle:Rectificados:perfil }