<?php

namespace Piddo\PresupuestoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CasilleroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasilleroRepository extends EntityRepository
{
}
