repuesto_portada:
    pattern:  /repuesto
    defaults: { _controller: RepuestoBundle:Default:repuesto }

repuesto_lista_solicitudes:
    pattern:  /repuesto/solicitudes
    defaults: { _controller: RepuestoBundle:Default:listaSolicitudes }

repuesto_presupuestos:
    pattern:  /repuesto/presupuestos
    defaults: { _controller: RepuestoBundle:Default:listaPresupuestos }

repuesto_lista:
    pattern:  /repuesto/lista
    defaults: { _controller: RepuestoBundle:Default:lista }