<?php

namespace Piddo\MotorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeloRepository extends EntityRepository
{
}
