<?php

namespace Piddo\MotorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeloRepository extends EntityRepository
{
    public function deleteModelo($modelo)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('DELETE MotorBundle:Modelo m WHERE m.id = :modelo');
        $consulta->setParameter('modelo',$modelo);
        $consulta->getResult();
    }
    public function findModelos($marca)
    {
        $em = $this->getEntityManager();
 
        $dql = 'SELECT mo  FROM MotorBundle:Modelo mo
                WHERE mo.marca = :marca
                ORDER BY mo.nombre ASC';

 
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('marca', $marca);
 
        return $consulta->getResult();
    }
}
