<?php

namespace Piddo\MotorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieRepository extends EntityRepository
{
    public function deleteSerie($serie)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('DELETE MotorBundle:Serie s WHERE s.id = :serie');
        $consulta->setParameter('serie',$serie);
        $consulta->getResult();
    }
    
    public function findSeries($modelo)
    {
        $em = $this->getEntityManager();
 
        $dql = 'SELECT s  FROM MotorBundle:Serie s
                WHERE s.modelo = :modelo
                ORDER BY s.nombre ASC';

 
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('modelo', $modelo->getId());
 
        return $consulta->getResult();
    }
}
