<?php

namespace Piddo\TallerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ColRectificadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColRectificadoRepository extends EntityRepository
{
}
