usuario_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: UsuarioBundle:Default:index }
    
usuario_privado:
    pattern:  /privado
    defaults: { _controller: UsuarioBundle:Default:privado }
# usuarios de prueba
usuario_gerente:
    pattern:  /gerente
    defaults: { _controller: UsuarioBundle:Default:gerente }

usuario_recepcion:
    pattern:  /recepcion
    defaults: { _controller: UsuarioBundle:Default:recepcion }
  
usuario_jefe_taller:
    pattern:  /jefetaller
    defaults: { _controller: UsuarioBundle:Default:jefeTaller }
    
usario_repuestos:
    pattern:  /repuestos
    defaults: { _controller: UsuarioBundle:Default:repuestos }  
    
usuario_administracion:
    pattern:  /administracion
    defaults: { _controller: UsuarioBundle:Default:administracion }
    
usuario_desarme:
    pattern:  /desarme
    defaults: { _controller: UsuarioBundle:Default:desarme }
    
usuario_taller:
    pattern:  /taller
    defaults: { _controller: UsuarioBundle:Default:taller } 
#fin usuarios de prueba    
usuario_registro:
    pattern:  /registro
    defaults: { _controller: UsuarioBundle:Default:registro }

usuario_logout:
    path: /logout

usuario_login_check:
    path: /login_check
    
usuario_login:
    pattern:  /login
    defaults: { _controller: UsuarioBundle:Default:login }