<?php

namespace Piddo\RespuestoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CantRepuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CantRepuestoRepository extends EntityRepository
{
}
