<?php

namespace Piddo\RespuestoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RepuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepuestoRepository extends EntityRepository
{
}
